### ISSUE TITLE
请问spider节点分布算法参考的的什么资料.

### ISSUE THREAD

**Issue by sickHamm** [alanyang/dhtspider#3]
> `static neighbor(target, id) {
>         return Buffer.concat([target.slice(0, 6), id.slice(6)])
>     }`

**Comment by alanyang** [comment]
kad算法就是异或，高位一样距离就近。目的是加入对方的routing table。可以去看http://engiy.com/tech  Routing table一节

**Comment by sickHamm** [comment]
谢谢回复,我问的是spider结点分布算法,不是kat, `neighbor(target, id) { return Buffer.concat([target.slice(0, 6), id.slice(6)]) }` 为什么取6;  "6"越大应该是spider结点分布越密,收到get_peer的概率越大,但覆盖dht网络需要的结点越多,反之"6"越小结点分布越稀疏.但覆盖的范围可以更大.

```
walk() {
        const node = this.table.shift()
        if (node) {
            this.findNode(Node.neighbor(node.id, this.table.id), {address: node.address, port: node.port})
        }
        setTimeout(()=>this.walk(), 2)
    }
```
