### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by loopq** [alanyang/dhtspider#4]
Hey,作者你好，我这段时间在研究dht爬虫，自己也写了一个，效果不是很好，就准备down下来大神的源码看一看，运行的过程中出了一些问题，不知道是不是我的环境不对？请教
-------------------- 分割线 上面是废话---------------------
问题：拿到代码跑了一晚上之后，发现输出的全部都是unensure的infohash，即get_peers 返回的infohash，announce_peer 一次也没有，所以很纳闷。这是我的问题，希望作者可以解答一下

**Comment by ProphetZarquon** [comment]
I just want to say that using translation is (almost) totally inadequate.

This is what Google gave me back:

Hey, author Hello, I am in this study dht reptile, he wrote a, the effect is not very good, down to prepare the god down to see the source, the process of running out of some problems, do not know is not My environment is not right? consult
-------------------- above the dividing line is nonsense ---------------------
Question: get the code ran a night after the output of all unensure is found infohash, that get_peers return infohash, announce_peer not once, so I wonder. This is my question, I hope the author can answer

**Comment by loopq** [comment]
OK, I mean, annouce_peer didn't respond at once.

**Comment by alanyang** [comment]
找台服务器放公网上吧。可能是你的内网问题，或者加上改改代码加上NAT https://github.com/indutny/node-nat-upnp

**Comment by loopq** [comment]
i got it
