### ISSUE TITLE
Complete Guide about How to make it working?

### ISSUE THREAD

**Issue by j0hnsn0w** [alanyang/dhtspider#5]
Hi,
Is there possible to make a complete guide about how to make it working like on your sample website?
I mean, I did make it running and listening on port 6339, then i see scrolling hashes like this: https://vgy.me/AsjRDT.jpg , then what im supposed to do after?

I hope to get an answer, thank you!

**Comment by alanyang** [comment]
the repo just a dht network spider. website?you still have a lot of work to do
