### ISSUE TITLE
请教下Node.neighbor 的作用和操作目的在哪？

### ISSUE THREAD

**Issue by catchstar** [alanyang/dhtspider#8]
看见Node模块里有一个neighbor的方法， 不知该方法的作用是什么， 并且为什么要进行slice的操作？

**Comment by fanpei91** [comment]
@catchstar 大部分的dht的routing table实现是[Kademlia](http://www.ic.unicamp.br/~bit/ensino/mo809_1s13/papers/P2P/Kademlia-%20A%20Peer-to-Peer%20Information%20System%20Based%20on%20the%20XOR%20Metric%20.pdf)，为了增加自己被其他节点所知，也增加自己存在于对方路由表的几率，把自己的id尽量跟对方的距离相近，而距离是使用xor运算, 10 xor 10 = 0，异或运算值越小，距离越近。所以如果你的id(20字节)的前159bits跟对方一样，那么你离对方的距离就不能再更近了，xor为1, 绝对会存在于对方的路由表中，离对方最近的就是对方他自己了, xor值为0. 

节点存离自己越近的节点很多，存离自己很远的节点很少。我这里有份kad routing table的实现[https://github.com/fanpei91/ktable](https://github.com/fanpei91/ktable)

https://github.com/fanpei91/ktable/blob/master/table.go#L110 从这行开始阅读，就知道为什么了。

**Comment by catchstar** [comment]
@fanpei91  非常感谢你详细的介绍， 学习了！

**Comment by ProphetZarquon** [comment]
Almost every time I read one of these, I learn something new. Fascinating project!
